name: flutter_qr_bar_scanner
description: "A Flutter Plugin for reading/scanning QR & Bar codes using Firebase's Mobile Vision API"
version: 3.0.2
homepage: https://github.com/contactlutforrahman/flutter_qr_bar_scanner

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.github.contactlutforrahman.flutter_qr_bar_scanner
        pluginClass: FlutterQrBarScannerPlugin
      ios:
        pluginClass: FlutterQrBarScannerPlugin

dependencies:
  flutter:
    sdk: flutter
  native_device_orientation: ^1.0.0
